#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyWyGTDzzqq9YjuMqsrcXRMhZVrCbD+cnL2YLpTLbTli2jXcX6mISWVzrPQWEkF5OPWCVtWpUpyEgjwe7m7E5zvpI0bGiPrdzrPmO5SMhFI0gRJK5VdJEVl59XColb4ueqh3cwvpbX2kMV8fq04WY+So8mGFlZ+EB+SdvWkgdzde0KOoX8pZQje/rD6GpHF9Jjul075D1kmlS4aUlUmGkM3c6Z5j/phLjyTRayKOD/dZyTEVSGZaS9csd3Qu/b98qoH9VpvG7+ri+RNMh3IYkIpORJjhlCxxvb6uTR89WcvNT94kNBA0GUECQkguElLjx9WSR0RwimfOv4b+Ewj/sX tbz_aws_atilgan
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDALtHV7YD9MN05PesCgCnoIrlLgn7vLSbicNR0EGUs4hWcn2Th4LezFOm2rhAX0s4Dhe/2rW71mvxRIK8tHSKO6NHZnI3FiY9LcJ9TUs/DJcYooML5qCRvi4R8ANMDgRiVGCdbu5g4XivgdU3ZYWlx3x4FBqipsl4XCTTvmy5AAdR+2koX+JwNSPR5T9gPiujaV5Ro1URj4DgnFFdtNz4VWTRw0UE4K8wMZP0aJl1Oxah/1gNXTRQZ9zldkxEQqv6Fqgh2xKbrsW6mJfcLiJUIdr5nSiqgFVVxXTxei2kbMGs7+QSNUkrZYHp/jgGEgurM4B0EnokC+C2f3xhCxpSZ aws-key       
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - adminer
  - php-mysqli

write_files:
  - path: /var/www/html/db.php
    content: |
      <?php
          $servername = "127.0.0.1";
          $username = "admin";
          $password = "pw";
          $dbname = "mysql";

          $conn = new mysqli($servername, $username, $password, $dbname);
          if ($conn->connect_error) {
              die("Connection failed: " . $conn->connect_error);
          }

          $sql = "select Host, User from mysql.user;";
          $result = $conn->query($sql);
          while ($row = $result->fetch_assoc()) {
              echo("<li>" . $row["Host"] . " / " . $row["User"] . "</li>");
          }
      ?>
  - path: /var/www/html/info.php
    content: |
      <?php
        phpinfo();
      ?>

  - path: /var/www/html/index.html
    content: |
      <html>
        <head><title>Willkommen</title></head>
        <body><h1>Willkommen auf dem Webserver!</h1></body>
      </html>

runcmd:
  - [sh, -c, "sudo a2enconf adminer"]
  - [sh, -c, "sudo systemctl restart apache2"]
  - [sh, -c, "sudo ufw allow 80/tcp"]
  - [sh, -c, "sudo ufw allow 22/tcp"]
  - [sh, -c, "sudo ufw enable"]
